namePrefix: main-

resources:
  - ../../base
  - pgadmin.yaml

configMapGenerator:
  - name: pgadmin-servers
    namespace: infra
    files:
      - servers.json

labels:
  - pairs:
      app.kubernetes.io/instance: main-postgres
    includeSelectors: true

secretGenerator:
  - name: postgres-secret
    namespace: infra
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true
