namePrefix: purpose-

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/instance: purpose-postgres
    includeSelectors: true

patches:
  - target:
      kind: PersistentVolumeClaim
      name: postgres-data
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 10Gi

secretGenerator:
  - name: postgres-secret
    namespace: infra
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true
